import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased min-h-screen bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-white via-blue-100/60 to-purple-200/80 backdrop-blur-2xl">
        <div className="fixed inset-0 z-0 pointer-events-none">
          {/* Top right accent */}
          <div className="absolute w-1/3 h-1/3 top-0 right-0 bg-gradient-to-br from-pink-300/60 via-purple-300/40 to-blue-200/40 rounded-full blur-2xl opacity-70" />
          {/* Center left accent */}
          <div className="absolute w-1/3 h-1/2 top-1/3 left-0 bg-gradient-to-tr from-blue-300/50 via-cyan-200/40 to-purple-200/30 rounded-full blur-2xl opacity-60" />
          {/* Center center accent */}
          <div className="absolute w-1/2 h-1/3 top-1/2 left-1/4 bg-gradient-to-br from-purple-200/40 via-pink-200/40 to-blue-200/40 rounded-full blur-2xl opacity-50" />
          {/* Bottom right accent (subtle) */}
          <div className="absolute w-1/3 h-1/3 bottom-0 right-0 bg-gradient-to-tr from-purple-300/30 via-pink-200/30 to-blue-200/30 rounded-full blur-2xl opacity-40" />
        </div>
        <div className="relative z-10 min-h-screen">
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 flex flex-col">
              <div className="px-10 pt-3 w-full">
                <Topbar />
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
